            - Image:
                source: https://lirp.cdn-website.com/efffae31/dms3rep/multi/opt/lawn-pest-control-services-640w.jpeg
                style:
                  position: absolute
                  top: 0
                  left: 0
                  width: 100%
                  height: 100%
            - View:
                style:
                  display: flex
                  flexDirection: column
                  alignItems: center
                  justifyContent: 'center'
                  width: 70%
                  height: 20%
                  borderWidth: 3
                  borderColor: khaki
                  borderRadius: 5
                  background: burlywood
                  boxShadow: "0px 0px 10px #00000044"
                children:
                  - Text:
                      style:
                        color: lemonchiffon
                        fontSize: 70
                        fontWeight: bold
                      index: 0
            - View:
                style:
                  width: 40%
                  height: 70%
                  border width: 50
                  borderWidth: 3
                  borderRadius: 10
                  borderColor: khaki
                  backgroundColor: burlywood
                  boxShadow: "0px 0px 10px #00000044"
                  flexDirection: column
                  alignItems: center
                  justifyContent: 'space-evenly'
                children: