
- View:
    style:
      borderWidth: 4
      width: 800
      height: 400
      borderColor: lightgray
      backgroundColor: green
      display: flex
      flexDirection: column
      alignItems: center
      justifyContent: 'space-between'
    children:
      - Image:
          source: https://lirp.cdn-website.com/efffae31/dms3rep/multi/opt/lawn-pest-control-services-640w.jpeg
          style:
            position: absolute
            top: 0
            left: 0
            width: 100%
            height: 100%
      - View:
          style:
            display: flex
            flexDirection: column
            alignItems: center
            justifyContent: 'center'
            width: 100%
            height: 20%
            border width: 50
            borderRadius: 5
            borderWidth: 5
            borderColor: 'transparent'
            backgroundColor: 'transparent'
          children:
            - Text:
                style:
                  color: 
                  fontSize: 70
                index: 0
            - Button:
                style:
                  width: 81
                  height: 50
                  borderColor: lightgray
                  borderWidth: 3
                  borderRadius: 10
                  backgroundColor: green
                  position: absolute
                  left: 650
                  justifyContent: 'center'
                on_touch:
                  backgroundColor: rgb(255, 200, 0)
                children:
                  - Text:
                      style:
                        color: white
                        fontSize: 34
                      index: 62                

      - ScrollView:
         style:
           width: 100%
           backgroundColor:
         children:
