            - View:
                style:
                  height: 90%
                  width: 100%
                  display: flex
                  flexDirection: row
                  alignItem: center
                  justifyContent: 'space-evenly'
                children:
                  - View:
                      style:
                        height: 100%
                        zIndex: 2
                        flex: 1
                        background: slategrey
                        display: flex
                        flexDirection: column
                        alignItems: center
                        justifyContent: 'space-evenly'
                        boxShadow: '0px 0px 10px #00000076'
                      children:
                        - View:
                            style:
                              height: 70%
                              width: 90%
                              background: white
                              borderRadius: 20
                              overflow: hidden
                            children:
                              - Image:
                                  source: https://i.insider.com/5df272bffd9db22295266cd8?width=1136&format=jpeg
                                  style:
                                    width: 100%
                                    height: 100%
                                    resizeMode: cover
                        - View:
                            style:
                              height: 10%
                              width: 70%
                              background: lightslategrey
                              display: flex
                              alignItems: center
                              justifyContent: center
                              borderRadius: 5
                            children:
                              - Text:
                                  index: 0
                                  style:
                                    color: white
                  - View:
                      style:
                        height: 100%
                        flex: 2
                        background: burlywood
                        display: flex
                        flexDirection: column
                        alignItems: center
                      children:
                        - View:
                            style:
                              position: sticky
                              zIndex: 2
                              height: 10%
                              width: 100%
                              background: khaki
                              boxShadow: '0px 0px 10px #00000044'
                              display: flex
                              alignItems: center
                              justifyContent: center
                            children:
                              - Text:
                                  index: 9
                                  style:
                                    color: slategrey
                                    fontWeight: bold
                                    fontSize: 20
                        - View:
                            style:
                              flex: 1
                              width: 100%
                              display: flex
                              flexDirection: column
                              alignItems: center
                              overflowY: scroll
                            children:
